Models/Activity.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace beltexam.Models
{
    public class Activity : BaseEntity
    {
        public int ActivityId {get;set;}
        public string Title { get; set; }
        // public string Time {get;set;}
        public DateTime StartTime { get; set; }
        public TimeSpan Duration { get; set; }
        // public int ThisDur {get; set;}
        // public string Unit {get; set;}
        public string Desc { get; set;}
        public int UserId { get; set; }

        public DateTime CreatedAt {get; set;}
        public User User { get; set; }
        public List<Rsvp> Participants { get; set; }

        public Activity(){
            Participants = new List<Rsvp>();
        }
    }
}

Controllers/ActivityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using beltexam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace beltexam.Controllers
{
    public class ActivityController : Controller
    {

        private BeltContext _context;
 
        public ActivityController(BeltContext context)
        {
            _context = context;
        }
 
        [HttpGet]
        [Route("/Home")]
        public IActionResult Index()
        {
            if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }

            ViewBag.AllActivities = _context.Activities.Include(b => b.Participants).Include(d =>d.User).Where(a => a.StartTime + a.Duration > DateTime.Now).OrderBy(c => c.StartTime).ToList();
            ViewBag.Id = HttpContext.Session.GetInt32("id");
            ViewBag.Name = _context.Users.SingleOrDefault(a => a.UserId == HttpContext.Session.GetInt32("id"));
            return View();
            // Other code
        }

        [HttpPost]
        [Route("/newactivity")]
        public IActionResult NewActivity(PlanViewModel model)
        {
            if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }   
            if(ModelState.IsValid){
                TimeSpan duration;
                if(model.Unit == "days"){
                    duration = new TimeSpan(model.Duration,0,0,0);
                }
                else if(model.Unit == "hours"){
                    duration = new TimeSpan(0,model.Duration,0,0);
                }
                else{
                    duration = new TimeSpan(0, 0, model.Duration, 0);
                }
                DateTime starttime = model.Date+model.Time;
                if(starttime < DateTime.Now){
                    ViewBag.TimeError = 2;
                    return View("New");
                }
                Activity NewAct = new Activity {
                    Title = model.Title,
                    Desc = model.Desc,
                    StartTime = starttime,
                    Duration = duration,
                    // ThisDur = model.Duration,
                    // Unit = model.Unit,
                    CreatedAt = DateTime.Now,
                    UserId = (int)HttpContext.Session.GetInt32("id"),
                };
                _context.Add(NewAct);
                _context.SaveChanges();
                Activity thisactivity = _context.Activities.OrderByDescending(a=>a.CreatedAt).FirstOrDefault();
                int num = thisactivity.ActivityId;
                return Redirect("/activity/"+num);
            }
            return View("New");
        }

        [HttpGet]
        [Route("/delete/{num}")]
        public IActionResult Delete(int num){
            if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
            Activity thisact = _context.Activities.Include(b => b.Participants).SingleOrDefault(a => a.ActivityId == num);
            foreach(Rsvp part in thisact.Participants){
                _context.Rsvps.Remove(part);
            }
            _context.Activities.Remove(thisact);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

       [HttpGet]
       [Route("/rsvp/{num}")]
       public IActionResult Rsvp(int num){
           if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
           List<Activity> allActs = _context.Activities.Include(a => a.Participants).ToList();
           Activity thisAct = _context.Activities.SingleOrDefault(a => a.ActivityId == num);
           ViewBag.Sched = 0;
           foreach(var act in allActs){
               foreach(var part in act.Participants){
                   if(part.UserId == HttpContext.Session.GetInt32("id")){
                       if(act.StartTime < thisAct.StartTime && thisAct.StartTime < act.StartTime+act.Duration ){
                           ViewBag.SchedError = 1;   //Check to see if desired activity starts during any of your current activities.
                           ViewBag.AllActivities = _context.Activities.Include(b => b.Participants).Include(d =>d.User).Where(a => a.StartTime + a.Duration > DateTime.Now).OrderBy(c=>c.StartTime).ToList();
                           ViewBag.Name = _context.Users.SingleOrDefault(a => a.UserId == HttpContext.Session.GetInt32("id"));
                           ViewBag.Id = HttpContext.Session.GetInt32("id");
                           return View("Index");
                       }
                       if(thisAct.StartTime < act.StartTime && thisAct.StartTime+thisAct.Duration > act.StartTime){
                           ViewBag.SchedError = 1;  //Check to see if any current activities start during your desired activity.
                           ViewBag.AllActivities = _context.Activities.Include(b => b.Participants).Include(d =>d.User).Where(a => a.StartTime + a.Duration > DateTime.Now).OrderBy(c=>c.StartTime).ToList();
                           ViewBag.Name = _context.Users.SingleOrDefault(a => a.UserId == HttpContext.Session.GetInt32("id"));
                           ViewBag.Id = HttpContext.Session.GetInt32("id");
                           return View("Index");
                       }
                   }
               }
           }
           Rsvp newRsvp = new Rsvp {
               UserId = (int)HttpContext.Session.GetInt32("id"),
               ActivityId = num
           };
           _context.Rsvps.Add(newRsvp);
           _context.SaveChanges();
           return RedirectToAction("Index");
       }

       [HttpGet]
       [Route("/unrsvp/{num}")]
       public IActionResult Unrsvp(int num){
           if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
           Activity thisact = _context.Activities.Include(a => a.Participants).SingleOrDefault(a => a.ActivityId == num);
           foreach(Rsvp part in thisact.Participants){
               if(part.UserId == (int)HttpContext.Session.GetInt32("id")){
                   _context.Rsvps.Remove(part);
               }
           }
            _context.SaveChanges();
           return RedirectToAction("Index");
       }

       [HttpGet]
       [Route("/activity/{num}")]
       public IActionResult Activity(int num){
           if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
            ViewBag.Id = HttpContext.Session.GetInt32("id");
           ViewBag.Activity = _context.Activities.Include(c => c.Participants).ThenInclude(a => a.User).Include(b => b.User).SingleOrDefault(d => d.ActivityId == num);
           return View();
       }

       [HttpGet]
       [Route("/new")]
       public IActionResult New(){
           if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
           return View();
       }
    }
}

Views/Activity/Activity.cshtml
<html>
    <head>
       <meta charset='utf-8'>
       <title>Weddings</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <div wrapper>
        <div class="topbar">
            <h1 class="top">Dojo Activity Center</h1>
            <a href="/logout">Log Off</a> &nbsp; &nbsp;
            <a href="/Home">Home</a>
        </div>
        <h1>@ViewBag.Activity.Title</h1>
        <div class="others">
        <h3>Event Coordinator: @ViewBag.Activity.User.FirstName </h3>
        <h3>Description:</h3>
        <p class="desc">@ViewBag.Activity.Desc</p>
        <h3>Participants:</h3>
        @{
            Boolean isin = false; 
            foreach(var part in ViewBag.Activity.Participants){
                if(part.UserId != ViewBag.Id){
                    <span>@part.User.FirstName</span> <br>
                }
                else{
                    isin = true; 
                }
            }
            <h4>Action:</h4>
            @if(ViewBag.Activity.UserId == ViewBag.Id){
                <a href=/delete/@ViewBag.Activity.ActivityId>Delete</a>
            }
            else{
                if(isin == true){
                    <a href=/unrsvp/@ViewBag.Activity.ActivityId>Leave</a>
                }
                else{
                    <a href=/rsvp/@ViewBag.Activity.ActivityId>Join</a>
                }
            } 
        }
        </div>
        </div>
    </body>
</html>

Views/Activity/Index.cshtml
<html>
    <head>
       <meta charset='utf-8'>
       <title>Weddings</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <div class="wrapper">
            <div class="topbar">
                <h1 class="top">Dojo Activity Center</h1>
                Welcome @ViewBag.Name.FirstName! &nbsp; &nbsp;
                <a href="/logout">Log Off</a> 
            </div>
            <br><br>
            <table>
                <tr>
                    <th>Activity</th>
                    <th>Date and Time</th>
                    <th>Duration</th>
                    <th>Event Coordinator</th>
                    <th>Number of Participants</th>
                    <th>Actions</th>
                </tr>
                @{
                    foreach(var act in ViewBag.AllActivities){
                        <tr>
                            <td><a href=/activity/@act.ActivityId>@act.Title</a></td>
                            <td>@act.StartTime.ToString("M/d, yyyy @ h:mm tt")</td>
                            @if(act.Duration.Days > 0){
                                <td>@act.Duration.Days days</td>
                            }
                            else if(act.Duration.Hours > 0){
                                <td>@act.Duration.Hours hours</td>
                            }
                            else{
                                <td>@act.Duration.Minutes minutes</td>
                            }
                            <td>@act.User.FirstName</td>
                            <td>@act.Participants.Count</td>
                            
                            @if(act.UserId == ViewBag.Id){
                                <td><a href=/delete/@act.ActivityId>Delete</a></td>
                            }
                            else{
                                Boolean isrsvp = false; 
                                foreach(var part in act.Participants){
                                    if(part.UserId == ViewBag.Id){
                                        isrsvp = true;
                                        break;
                                    }
                                }
                                if(isrsvp == true){
                                    <td><a href=/unrsvp/@act.ActivityId>Leave</a></td>
                                }
                                else{
                                    <td><a href=/rsvp/@act.ActivityId>Join</a></td>
                                }
                            }
                        </tr>
                    }    
                }
            </table>
            <br><br>
            <form action="/New">
                <button type="submit">Add New Activity!</button>
            </form>
            <br>
            @{
                if(ViewBag.SchedError == 1){
                    <p>One or more activities you are participating in conflicts with this activity, so you cannot join it!</p>
                }
            }
        </div>
            
    </body>
</html>

Views/Activity/New.cshtml
@model beltexam.Models.PlanViewModel
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>Index</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <div class="wrapper">
            <div class="topbar">
                <h1 class="top">Dojo Activity Center</h1>
                <a href="/logout">Log Off</a> &nbsp; &nbsp;
                <a href="/Home">Home</a>
            </div>
            <h1>Create an Activity</h1>
            <div class="init">
            <form asp-controller="Activity" asp-action="NewActivity" method="post">
                <label asp-for="Title">Title:</label>
                <input asp-for="Title"/><br>
                <label asp-for="Time">Time:</label>
                <input asp-for="Time"/><br>
                <label asp-for="Date">Date:</label>
                <input asp-for="Date"/><br>
                <label asp-for="Duration">Duration:</label>
                <input asp-for="Duration"/> 
                <select asp-for="Unit">
                    <option value="days">Days</option>
                    <option value="hours">Hours</option>
                    <option value="minutes">Minutes</option>
                </select> <br>
                <label asp-for="Desc">Description:</label> <br>
                <textarea asp-for="Desc" rows="10" cols="50"/></textarea> <br>
                <button type="submit">Create Activity</button>
            </form>
            <br>
            <div asp-validation-summary="All"></div>
            @{
                if(ViewBag.TimeError == 2){
                    <p>Activities must be planned in the future!</p>
                }
            }
            </div>
        </div>
    </body>
</html>